### ISSUE TITLE
rsasigkey problem

### ISSUE THREAD

**Issue by Mikchel** [xelerance/Openswan#127] opened 2015-06-06 05:27 UTC
Current version does read public left/right rsasigkeys from config ipsec.conf but by some magic way forget about them and until not load this keys manually with ipsec whack authentication isn't working

**Comment by mcr** [comment] 2015-06-08 14:37
Hi, the 2.6.43 version likely does have this problem due to a regression that we introduced in January. It seems that we have few rsasigkey= tests, which is unfortunate.  It is fixed in code that is about to be release as soon as a different problem is fixed; if you want a source code patch I can post that.

**Comment by Mikchel** [comment] 2015-06-08 16:13
No, thank you, I will wait for release. I need to test tunnel between pc and our mobile device. In general it is working. That is enough in this time.

WBR,

Rumyantsev Egor

----- Reply message -----
От: "Michael Richardson" <notifications@github.com>
Кому: "xelerance/Openswan" <Openswan@noreply.github.com>
Копия: "Mikchel" <mikchel@mail.ru>
Тема: [Openswan] rsasigkey problem (#127)
Дата: пн, июн 8, 2015 19:37
Hi, the 2.6.43 version likely does have this problem due to a regression that we introduced in January. It seems that we have few rsasigkey= tests, which is unfortunate.  It is fixed in code that is about to be release as soon as a different problem is fixed; if you want a source code patch I can post that.  

&mdash;

**Comment by Mikchel** [comment] 2015-06-28 08:46
Tell me please when do you have plans to release next version?
If it will happen later than July, then please send me patches to fix rsasigkey issue

WBR,

**Comment by mcr** [comment] 2015-06-29 17:51
Hi, the 2.6.44 release is being cut this week.
The patches to fix that are at: https://github.com/xelerance/Openswan/commit/4b4dcea25664d1b1e8f7a9e5a1229f3963199ba0

**Comment by Mikchel** [comment] 2015-07-11 05:49
Hello,
After pulling master rsa key problem fixed ( tested armv7 handheld device and x86 notebook ).
Hope it is closed

**Closed** 2015-07-11 05:49 UTC
