### ISSUE TITLE
CentOS 6.5 64 bit, make programs error, 2.6.43 is ok

### ISSUE THREAD

**Issue by austgl** [xelerance/Openswan#171] opened 2016-02-04 09:26 UTC
/root/openswan-2.6.46/include/pluto/log.h:151: error: redefinition of typedef ‘logfunc’
/root/openswan-2.6.46/include/pluto/log.h:151: note: previous declaration of ‘logfunc’ was here
make[3]: *** [connections.o] Error 1
make[3]: Leaving directory `/root/openswan-2.6.46/OBJ.linux.x86_64/programs/pluto'
make[2]: *** [programs] Error 1
make[2]: Leaving directory `/root/openswan-2.6.46/OBJ.linux.x86_64/programs'
make[1]: *** [programs] Error 1
make[1]: Leaving directory `/root/openswan-2.6.46/OBJ.linux.x86_64'
make: *** [programs] Error 2

----------------------------------------

make[3]: Leaving directory `/root/openswan-2.6.43/OBJ.linux.x86_64/programs/pf_key'
make[3]: Entering directory `/root/openswan-2.6.43/OBJ.linux.x86_64/programs/_updown.mast'
IN _updown.mast.in -> _updown.mast
make[3]: Leaving directory `/root/openswan-2.6.43/OBJ.linux.x86_64/programs/_updown.mast'
make[3]: Entering directory `/root/openswan-2.6.43/OBJ.linux.x86_64/programs/_startnetkey'
IN _startnetkey.in -> _startnetkey
make[3]: Leaving directory `/root/openswan-2.6.43/OBJ.linux.x86_64/programs/_startnetkey'
make[3]: Entering directory `/root/openswan-2.6.43/OBJ.linux.x86_64/programs/_updown.netkey'
IN _updown.netkey.in -> _updown.netkey
make[3]: Leaving directory `/root/openswan-2.6.43/OBJ.linux.x86_64/programs/_updown.netkey'
make[2]: Leaving directory `/root/openswan-2.6.43/OBJ.linux.x86_64/programs'
make[1]: Leaving directory `/root/openswan-2.6.43/OBJ.linux.x86_64'
[root@iZ62nfbnzj5Z openswan-2.6.43]# cd ../openswan-2.6.4
openswan-2.6.43/        openswan-2.6.43.tar.gz  openswan-2.6.46/     

------------------------------------------------------
[root@iZ62nfbnzj5Z openswan-2.6.46]#  cat /etc/issue
CentOS release 6.5 (Final)
Kernel \r on an \m

[root@iZ62nfbnzj5Z openswan-2.6.46]# uname -a
Linux iZ62nfbnzj5Z 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
[root@iZ62nfbnzj5Z openswan-2.6.46]# uname -r
2.6.32-431.23.3.el6.x86_64
[root@iZ62nfbnzj5Z openswan-2.6.46]#

**Comment by PrashantSunkari** [comment] 2016-03-07 23:32
yes I have run this issue as well. Does anyone know a fix for this ?

**Comment by shussain** [comment] 2016-04-05 15:08
This issue occurred for me in CentOS 6.7   Ubuntu worked for me.

The issue is the multiple inclusions of pluto/log.h     Older versions of gcc will complain about it and giving the above error

This commit should fix the issue: https://github.com/xelerance/Openswan/commit/35b197db67077fa9401b0cbe7956437e69d301de

**Comment by freedai** [comment] 2016-05-09 19:00
After applying this patch, there were more errors for log.c. My build is openswan 2.6.47 though.

/builddir/build/BUILD/openswan-2.6.47/programs/pluto/log.c: In function 'connection_state':
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/log.c:952: error: 'struct connection' has no member named 'host_pair'
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/log.c:952: error: 'struct connection' has no member named 'host_pair'

**Comment by shussain** [comment] 2016-05-09 22:47
I could not reproduce on CentOS 6.5 and 6.7 using the patch.

Could you please delete the OBJ* folder (rm -rf OBJ*) and try again.

If the issue still occurs, can you please specify:
- what distro you are using
- any options or settings you are using (if you are not using _make programs_)

**Comment by freedai** [comment] 2016-05-10 16:15
It's based on CentOS 6.

```
/usr/bin/make 'USERCOMPILE=-g -O2 -g -march=i686 -fPIE -pie' 'USERLINK=-g -pie' HAVE_THREADS=true HAVE_STATSD=true USE_DYNAMICDNS=true USE_LWRES=true INC_USRLOCAL=/usr FINALLIBDIR=/usr/lib/ipsec MANTREE=/usr/share/man INC_RCDEFAULT=/etc/rc.d/init.d programs
Setting up for OBJDIR=OBJ.linux.i386
make[3]: Entering directory `/builddir/build/BUILD/openswan-2.6.47/OBJ.linux.i386/programs/pluto'
CC connections.c
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/connections.c: In function 'delete_end':
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/connections.c:191: warning: unused parameter 'c'
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/connections.c:191: warning: unused parameter 'sr'
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/connections.c: In function 'show_one_sr':
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/connections.c:2984: warning: unused parameter 'num'
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/connections.c: In function 'refine_host_connection':
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/connections.c:2242: warning: 'auth_policy' may be used uninitialized in this function
CC initiate.c
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/initiate.c: In function 'initiate_ondemand_body':
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/initiate.c:829: warning: 'next_step' may be used uninitialized in this function
CC terminate.c
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/terminate.c: In function 'terminate_a_connection':
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/terminate.c:79: warning: unused parameter 'arg'
CC pending.c
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/pending.c: In function 'add_pending':
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/pending.c:78: warning: unused parameter 'uctx'
CC cookie.c
CC crypto.c
CC dpd.c
CC foodgroups.c
CC log.c
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/log.c: In function 'connection_state':
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/log.c:952: error: 'struct connection' has no member named 'host_pair'
/builddir/build/BUILD/openswan-2.6.47/programs/pluto/log.c:952: error: 'struct connection' has no member named 'host_pair'
make[3]: Leaving directory `/builddir/build/BUILD/openswan-2.6.47/OBJ.linux.i386/programs/pluto'
make[3]: *** [log.o] Error 1
make[2]: Leaving directory `/builddir/build/BUILD/openswan-2.6.47/OBJ.linux.i386/programs'
make[2]: *** [programs] Error 1
make[1]: Leaving directory `/builddir/build/BUILD/openswan-2.6.47/OBJ.linux.i386'
make[1]: *** [programs] Error 1
make: *** [programs] Error 2

```

**Comment by mcr** [comment] 2016-05-10 16:39
Hi, this is a multiple-inclusion error in log.h, which C11 happens to cover up.
2.6.47.1 was released last week with just this fix; we are delayed on 2.6.48.

**Comment by libreswan** [comment] 2016-05-10 17:01
note that with today's release of RHEL-6.8, which will shortly find its way into centos6 too, that any openswan install will be obsoleted by libreswan when the system is updated.

**Comment by freedai** [comment] 2016-05-10 17:26
Is libreswan supporting nat-t? It used to be not. That's why we still build openswan other than libreswan.

**Comment by letoams** [comment] 2016-05-10 17:52
Of course it does. The option nat_traversal= was removed because it is always on

**Comment by freedai** [comment] 2016-05-10 17:58
Good to know. We can go this route in next release. Thanks.

**Comment by shussain** [comment] 2016-05-10 18:53
I have looked into the new compile error and the following should fix the compile error:

`diff --git a/programs/pluto/log.c b/programs/pluto/log.c
index 2a46c3f..f0a3c9c 100644
--- a/programs/pluto/log.c
+++ b/programs/pluto/log.c
@@ -949,7 +949,7 @@ connection_state(struct state *st, void *data)
                return;
 
        if (st->st_connection != lc->conn) {
-               if (lc->conn->host_pair != st->st_connection->host_pair ||
+               if (lc->conn->IPhost_pair != st->st_connection->IPhost_pair ||
                        !same_peer_ids(lc->conn, st->st_connection, NULL))
                    return;
                /* phase1 is shared with another connnection */
`

I am currently in the middle of a release. Once it is done, I will be creating a commit and can provide it in this ticket.

**Comment by shussain** [comment] 2016-05-12 21:18
Commit 05513000281e61790c8a4df442dfb68d024f376d in the 2.6.48dev now has the fix for the compile error when HAVE_STATSD=true

**Comment by shussain** [comment] 2016-09-19 13:51
2.6.48 (and 2.6.49) has been released. Closing this issue.

**Closed by shussain** 2016-09-19 13:51 UTC
